#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import Float64MultiArray
import time

def talker():
    pub = rospy.Publisher('/youbot_base/joints_vel_controller/command', Float64MultiArray, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(10)  # 10hz
    msg = Float64MultiArray()

    # 速度设置
    linear_velocity = 0.1  # 直线行驶速度
    angular_velocity = 0.1  # 转弯速度
    side_length = 0.5  # 正六边形边长，单位：米
    side_time = side_length / linear_velocity  # 每边行驶时间
    turn_time = 60.0 / angular_velocity  # 转弯所需时间（60度）

    for _ in range(7):  # 正六边形有六条边
        # 直线行驶
        start_time = time.time()
        while time.time() - start_time < side_time:
            # 所有轮子以相同速度旋转以实现直线行驶
            msg.data = [linear_velocity, linear_velocity, linear_velocity, linear_velocity]
            rospy.loginfo(msg)
            pub.publish(msg)
            rate.sleep()

        # 转弯
        start_time = time.time()
        while time.time() - start_time < turn_time:
            # 为了转弯，一侧的轮子以不同于另一侧的速度旋转
            msg.data = [-angular_velocity, angular_velocity, -angular_velocity, angular_velocity]
            rospy.loginfo(msg)
            pub.publish(msg)
            rate.sleep()

    # 停止所有轮子
    msg.data = [0, 0, 0, 0]
    pub.publish(msg)
    rospy.loginfo("Hexagon completed, stopping the robot.")

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
